"""empty message

Revision ID: 06f9ee9fc7f9
Revises: bfa4d5db1df1
Create Date: 2021-05-25 20:48:38.864673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f9ee9fc7f9'
down_revision = 'bfa4d5db1df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_game')
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default='NOW()', nullable=False))
        batch_op.alter_column('started_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('started_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('created_at')

    op.create_table('_alembic_tmp_game',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.Column('winner', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
