"""add 'uuid' column to players table

Revision ID: 0b0f21e4d479
Revises: c65130685be3
Create Date: 2021-07-20 20:47:05.140974

"""
from alembic import op
import sqlalchemy as sa
from doppelkopf.db_helpers import GUID


# revision identifiers, used by Alembic.
revision = '0b0f21e4d479'
down_revision = 'c65130685be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', GUID(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
