"""empty message

Revision ID: bfa4d5db1df1
Revises: d7ae53e5bbf4
Create Date: 2021-05-16 17:07:47.103528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa4d5db1df1'
down_revision = 'd7ae53e5bbf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disconnected_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('disconnected_at')

    # ### end Alembic commands ###
